### ISSUE TITLE
Update on Button Library

### ISSUE THREAD

**Issue by 32teeth** [DerNuntius/Gameboy-Zero-Pocket-Button-PCB#1]
# Hi there!
>Great work on your first PCB!

It look like you are making use of the [32teeth - Conductive Buttons.lbr](https://github.com/32teeth/Eagle-Libraries-by-32teeth/blob/master/lbr/32teeth%20-%20Conductive%20Buttons.lbr) library! Good stuff.

We recently released different packages for each of the buttons (see image)
![New Buttons](https://scontent-ort2-2.cdninstagram.com/vp/43861d3078c1e005c3fce4b1b1a071fb/5CDBA567/t51.2885-15/e35/47691613_358984294893610_2781550537166094142_n.jpg?_nc_ht=scontent-ort2-2.cdninstagram.com&se=8)
**Feel free to us those as well**

Look forward to seeing what you produce

**Comment by DerNuntius** [comment]
Hi,
Thank you for this tip. I think I'll use these buttons but first, I need to test my first revision to see if the dimensions are correct. But I'll start to make a second revision.

Best Regards Hugo
